### ISSUE TITLE
Visiting same page doesn't replace on stack

### ISSUE THREAD

**Issue by joemasilotti** [hotwired/hotwire-native-android#27]
In Hotwire Native iOS, visiting the same page that is currently being displayed will automatically replace it. On Hotwire Native Android, this pushes a new screen onto the stack.

Same is true for when visiting a page that is exactly the same as the _previous_ one on the stack.

Here is the relevant iOS code that handles both of these scenarios:
https://github.com/hotwired/hotwire-native-ios/blob/main/Source/Turbo/Turbo%20Navigator/TurboNavigationHierarchyController.swift#L114-L131

**Comment by jayohms** [comment]
Fixed in https://github.com/hotwired/hotwire-native-android/pull/75 and https://github.com/hotwired/hotwire-native-android/pull/74
