### ISSUE TITLE
App freezes after closing modal with X button

### ISSUE THREAD

**Issue by EmilioCristalli** [hotwired/hotwire-native-android#63]
When a path is configured to open as a modal, if you close the modal using the `X` button, the modal is dismissed but the app freezes.

If you close the modal by sliding it down, it works correctly.

Was able to reproduce the issue with the demo app:

https://github.com/user-attachments/assets/4453b7ae-4ddc-4541-9166-fe95f18fa530

**Comment by donnfelker** [comment]
Running into this issue as well. I'm going to dig into it tonight/tomorrow.
