### ISSUE TITLE
Empty `bridge-components` in default `userAgent`

### ISSUE THREAD

**Issue by EmilioCristalli** [hotwired/hotwire-native-android#64]
I was trying to follow the [docs](https://native.hotwired.dev/android/bridge-components) to create a bridge component, but i think the component wasn't loading because the default user agent is sending an empty list of components (`bridge-components: [];`)

If I understand correctly, `hotwire-native-bridge` checks that the list is not empty [here](https://github.com/hotwired/hotwire-native-bridge/blob/7839c71fee9163bcaf73b19c29a319e7a07fbe02/src/helpers/user_agent.js#L3) to decide if the component should load.

If the user agent is overridden with something like `Hotwire.config.userAgent = "MyApp; ${Hotwire.config.userAgentSubstring()}"`, the user agent now includes the right bridge-compoennts, and the component loads correctly.

Not sure if this is a bug or if i missed something in the docs, but it felt like the default userAgent should just work.

Was also able to reproduce this int he demo app, by commenting out the custom userAgent line [here](https://github.com/hotwired/hotwire-native-android/blob/d29bc541efc644b337beac356fead71d360b9d31/demo/src/main/kotlin/dev/hotwire/demo/DemoApplication.kt#L72). After doing this, the bridge components stop working

**Comment by donnfelker** [comment]
I had this same problem for a bit. The `hotwire-native-bridge` does expect that the array be non-empty. Which kind of makes sense if you think about it. If there are not bridge components registered then there is no reason to even load them on the client and waste potential resources. The client is telling the rails app "Hey, I can handle these bridge components". If your app is not using bridge components, then there's no reason for it to connect the stimulus controllers. 

I can see why you'd want it to work by default, so mabye setting the `Hotwire.config.userAgent` by default to the substring might suffice?

**Comment by aronwolf90** [comment]
I have the same error. I also vote for a good default.

**Comment by jayohms** [comment]
This was resolved in https://github.com/hotwired/hotwire-native-android/pull/77 and will be available in `v1.1` soon.
