### ISSUE TITLE
No longer can transit from native Activity to Hotwire Activity using navigator.route

### ISSUE THREAD

**Issue by diegocharles** [hotwired/hotwire-native-android#76]
After I migrated from turbo-native to hotwire-native, I no longer have the native activity transitioning to hotwire activity. 

Perhaps is just a simple issue and I must admit that I'm definitely not an expert in Android development, so I'd really appreciate some help. 

Below is the code for the function. I debugged it until the `navigator.route(signInUrl)` . 

There are no exceptions in the Tomcat's log. 

Attached is a video that I recorded. Notice that all that happens after I touch the Continue with Google, is the action bar blinking. 

```
   private fun handleSignInResult(completedTask: Task<GoogleSignInAccount>) {
        try {
            val account = completedTask.getResult(ApiException::class.java)
            // Signed in successfully, show authenticated UI.
            CookieManager.getInstance().setCookie(BASE_URL, "id_token=${account.idToken}") {
                val signInUrl = "${BASE_URL}/turbo_native/sessions/create"
                navigator.route(signInUrl)
            }
        } catch (e: ApiException) {
            showAlert("Sign-in failed", "Error: ${e.statusCode}")
        }
    }
```

https://github.com/user-attachments/assets/1d8e51e0-0698-4a88-8b39-7fcb194d7f56

**Comment by jayohms** [comment]
Hey @diegocharles this is intentional and a change in Hotwire Native. You'll note that there is no longer an API available to register `Activity` destinations like you can register `Fragment` destinations. Android (and Google) have been moving away from multi-Activity structured apps, and rather than provide an inconsistent experience in Hotwire Native for Activities, those must now be manually handled by the app with an `Intent`. Using multiple Activities in an app should be an exception, not the rule.

Corresponding PR: https://github.com/hotwired/hotwire-native-android/pull/10

To launch a new `Activity`, call:
```kotlin
val intent = Intent(context, AnotherActivity::class.java)
context.startActivity(intent)
```

**Comment by diegocharles** [comment]
Hi @jayohms 

I genuinely appreciate your support. Thank you!

I apologize for the confusion; I meant to say “Fragment” instead of “Activity.” 🤦‍♂️

I have implemented a GoogleSignInFragment as an Android native screen. I want to navigate to the “session/create” route, but for some reason, the “navigator.route(url)” function isn’t working since I migrated from Turbo Native to Hotwire Native.

In fact, it doesn’t navigate to any URL, not just “sessions/create.”

Do you have any advice on how to resolve this issue?

**Comment by jayohms** [comment]
@diegocharles I'd take a look at the demo app's (in this repo) [`DemoApplication`](https://github.com/hotwired/hotwire-native-android/blob/main/demo/src/main/kotlin/dev/hotwire/demo/DemoApplication.kt#L44-L53) class and make sure you're registering fragments correctly. You'll also want to make sure that the `DemoApplication` class is registered as your main `Application` class [in your manifest file](https://github.com/hotwired/hotwire-native-android/blob/main/demo/src/main/AndroidManifest.xml#L8).

Other than that:
- Make sure your path configuration uris match your destination uris
- Ensure that your urls match
- Ensure that you're [using the default route decision handlers](https://github.com/hotwired/hotwire-native-android/blob/main/demo/src/main/kotlin/dev/hotwire/demo/DemoApplication.kt#L62-L66) or have custom ones setup correctly

**Comment by diegocharles** [comment]
@jayohms I appreciate your help. Thank you buddy!
